db:
  development:
    adapter: sqlite3
    database: db/development.sqlite3
    pool: 1
    timeout: 5000
    encoding: "ecu-jp"
  production:
    adapter: sqlite3
    database: db/production.sqlite3
    pool: 1
    timeout: 5000
    encoding: "ecu"

